### ISSUE TITLE
Adding sampling time to GET request

### ISSUE THREAD

**Issue by wseis** [technologiestiftung/flusshygiene-radolan-data-api#2]
In the radolan filepath the last four digits of the datetime string refer to the time the 24h average is calcualted, so it is YYMMDDHHMM. Thus, the below example refers to 10 min before 1 a.m.. It would be great, if we could add the time-information into the GET request to avoid downloading unnecessary files.

"raa01-rw_10000-1901010050-dwd---bin"

**Comment by ff6347** [comment]
Good idea. We could make this optional and filter the results list by a specific string. If the string does not match anything the full list is returned. 
So we could also filter by `raa1-`
