### ISSUE TITLE
Radolan SF product to be added

### ISSUE THREAD

**Issue by wseis** [technologiestiftung/flusshygiene-radolan-data-api#3]
I tried the download option today. Everything went fine, downloadwise. However, I compared the data to BWB rain gauges (daily spatial averages) and the radolan data we downloaded previously and noticed quite some differences. Finally I noticed the radolan products are different. Our evaluation routines and R-Scripts are currently written for the radolan SF product. When I see it correctly, the amazon AWS server provides the radolan RW product. They unfortunately do not match.

**Comment by ff6347** [comment]
Arrrrrrggghh. 😢  And you can't work with the RW?
I overlooked that your are loading both in the kwbr/fhpredict package. I Just looked at the RW.
Scraping all the SF will take some time again. 
What is the difference?

**Comment by ff6347** [comment]
Let's have a quick call tomorrow morning.

**Comment by wseis** [comment]
ok

**Comment by ff6347** [comment]
Files are in transfer 🛫

**Comment by ff6347** [comment]
2006 - 2012 already 🛬 
2013 taking of 🛫
2019 taking of 🛫

**Comment by ff6347** [comment]
2019 🛩💥

**Comment by ff6347** [comment]
till 2018/09 🛬
2019 🛫

**Comment by wseis** [comment]
Thanks for adding the SF product. The only year which still gives error messages is year 2014. Can you see whether there are any differences between 2014 and the others?

**Comment by wseis** [comment]
@Hauke: Error message of R function says: ```Error in read_binary_radolan_file_raw_v3(file) : 
  grepl(" 900x 900", header) is not TRUE```

**Comment by ff6347** [comment]
I didnt deploy the new api yet. You should not have access

**Comment by hsonne** [comment]
@wseis The error is related to the kwb.dwd package. I put the issue there.

**Comment by ff6347** [comment]
So I ignore these last messages. I think I can deploy the new SF api on Monday

**Comment by ff6347** [comment]
SF is added
