### ISSUE TITLE
Empty file list if taking the file list takes too long?

### ISSUE THREAD

**Issue by hsonne** [technologiestiftung/flusshygiene-radolan-data-api#7]
The following request does not return any URLs but instead a status code of 502 with message "Internal server error":

`<ENDPOINT_PROD>?from=20080101&to=20180920&time=1050`

Why? It looks as if the behaviour were not reproducible (i.e. a request sometimes fails, sometimes not). Is there maybe a restriction set in the time that listing the files may take?

This URL sometimes worked and sometimes not (`Internal server error`):
`<ENDPOINT_PROD>?from=20080101&to=20100920&time=1050`

**Comment by ff6347** [comment]
@hsonne  This is related to the timeout of the function. I increased the period from 6000 to 60000 ms. But getting all values from 2008 till 2019 might take even longer. For getting it with a specific timestamp (like your request {{radoloan_api_host}}?from=20080101&to=20190131&time=2250) it took me around 23000 ms.

I'll close this issue for now. If you run into this again. Open a new one for increasing the timeout even further.
